### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by zeeshanch909** [Zain-ul-din/LGU-Timetable#15]
Assalamualaikum.  brother , I want to discuss an issue

**Comment by Zain-ul-din** [comment]
yes sure! please describe you're issue

**Comment by zeeshanch909** [comment]
We have successfully launched frontend and backend  individually, but they are not connecting , We didn't understand in which file  in frontend you are making requests to backend , Kindly guide me ,  and second thing is  Admin page is stuck on Loading Users....

**Comment by zeeshanch909** [comment]
If possible for you can you share your any social account so that we can disscuss it properly!

**Comment by Zain-ul-din** [comment]
@zeeshanch909 I'm not sure about which project you're talking about. if you're talking about [`LGU Time table`](https://www.lgutimetable.live/), I'll launch a full paper on how the [`LGU Time table`](https://www.lgutimetable.live/) works under the hood.


## Basic Overview

There are two separate repositories of this project
- [frontend](https://github.com/Zain-ul-din/LGU-Timetable) responsible for displaying all content to users.
- [Crawler](https://github.com/Zain-ul-din/lgu-crawler/tree/preview) scrap data from LGU official timetable and send it to Firebase.

 ### Tech Stack

- Database `firebase` and `Redis`
- Front-end `Next Js`

**Note!**

if you wanna build the same kind of timetable. Then, [LGU Timetable APIS](https://www.lgutimetable.live/developer) is a good starting point it'll not only give you access to `APIS` but it'll also teach you how to use these `APIS` in your app. if you have further questions let me know or you can meet me if you're from LGU.

Happy Codding ♥

**Comment by Zain-ul-din** [comment]
> If possible for you can you share your any social account so that we can disscuss it properly!

[My Timetable](https://www.lgutimetable.live/timetable/6th%20Semester%20Sp-2023%20-%20Fa-2020%20BSCS%20Sec%20E)

**Comment by zeeshanch909** [comment]
In Sha Allah will see you tomorrow in the university.
Here is my WhatsApp number .if possible contact me when you reached university, it will be pleasure for me.
03124832909
Zeeshan Zaka
Thanks and Regards🥰
