### ISSUE TITLE
Design home page for lgu timetable

### ISSUE THREAD

**Issue by Zain-ul-din** [Zain-ul-din/LGU-Timetable#3]
The homepage of the LGU timetable should contain a simple header at the top, four cards in the middle of the screen with logos, and a footer at the bottom. Each card will contain a link to a page.

```
 <!-- Header -->
 4 cards [ 'timetable', 'free classrooms', 'about us, 'hall of fame' ]
 <!-- footer -->
 <!-- <repo link> -->
```

view a basic overview of design on [Figma ](https://www.figma.com/file/fhohhocB0q6Yx1QW2uEVfP/Untitled?node-id=0%3A1&t=ggN9Blr2gxV1SA46-1) 

if you have a better suggestion let us know [here](https://github.com/Zain-ul-din/LGU-Timetable/discussions/categories/show-and-tell)

**Comment by Sahad-09** [comment]
Hey i would like to work on this :)

**Comment by Sahad-09** [comment]
Assign it to me

**Comment by Zain-ul-din** [comment]
@Sahad-09 done

**Comment by Zain-ul-din** [comment]
thanks for contribution
