### ISSUE TITLE
Update timetables more frequently.

### ISSUE THREAD

**Issue by platapusisgay** [Zain-ul-din/LGU-Timetable#34]
Timetables changing too frequently (esp. for BS DFCS Sec A spring semester 2024)
i.e on 26 march 2024 all day uptill 3:44 pm has been the timetable for 25 march 2024 which is invalid for 26 march 2024.
(New to github)

**Comment by platapusisgay** [comment]
The login is student@lgu.edu.pk and password is lgustud123 its valid for all the accessible data. I think letting the api do the session and logging stuff itself is a bit better since i dont think anyone will be willing to take their precious time trying to understand how to get a session id. I appreciate the feature and the thinking that went behind it but the problem was the API not updating the timetables frequently enough. The API can do this stuff i hope so... cant it?

**Comment by Zain-ul-din** [comment]
@platapusisgay Currently it is not possible to login into the website using the username and password cuz they have `apacha` on their website which is very hard to solve. There are some tools available online that can do it but nobody will be ready to sponsor this project.

**Comment by platapusisgay** [comment]
Oh yea i forgot about the captcha part. 
I guess students should contribute I agree

**Comment by Zain-ul-din** [comment]
@platapusisgay thanks! we're also looking for technical contributions nominate yourself in the election if you wanna contribute.

**Comment by platapusisgay** [comment]
Please guide me about the elections id love to contribute.

**Comment by Zain-ul-din** [comment]
@platapusisgay [read about elections here](https://www.lgutimetable.online/election)

**Comment by platapusisgay** [comment]
Since there are only two nominees standing for Moderator elections, why don't you make both of them the Moderators? So that two minds can work together. I'm no dev here just a hobbyist programmer who knows only a little bit about modifying existing code to my likings. However i can give ideas about features or making things work.

**Comment by Zain-ul-din** [comment]
@platapusisgay the moderator control will go from a higher-voted person to all the way down to the last person.
