### ISSUE TITLE
Want to join the LGU unofficial coding community (GPT) and host this project there?

### ISSUE THREAD

**Issue by ZainabDev** [Zain-ul-din/LGU-Timetable#41]
hello Zain, 

after giving much thoughts and also consulting from many teachers and taking permission i came to made a LGUs unofficial coding community called [Garrison Programming Titans](https://github.com/gpt-lgu), it is unofficial yet but if we make it enough successful we can make it official.

i believe your contribution would be valuable to our community. 

GPT aims to provide a platform for students to learn, share, and grow together in the field of programming. we also provide lessons on c++ fundamentals and oop. 

also i think your project would be great to showcase on our github page.

If you're interested, please join let me know.

**Comment by Zain-ul-din** [comment]
Hey, how are you?

Yeah! It looks good to me, and I'm always open to contributing to the community. overall it's pretty rad I'm so excited.

With that said, Sometime before I was planning a node js course with an Indian girl who was very good at writing blogs she is currently writing on Medium. We can make a team and offer paid courses as well.

Apart from that, I'm working on a secret project it is very painful for me to work alone on it but its reward will be worth the effort. lets see when it'll be available :-).

**Comment by ZainabDev** [comment]
hahaha 
well about the paid courses part 
do u wana make a seperate community for it or integrate it in GPT because GPT is only for students from LGU.
also im working on a solo project (codeneko) too its quite big and its overwhelming but yea it'll be big and ill be my legacy :")

**Comment by Zain-ul-din** [comment]
sorry separate community for what? if you are talking about this project then you can make a fork of it and ping me for a meeting or contact me on WhatsApp I'll help to set this up. 

for the paid courses my target audience is European people don't expect LGU student will pay you up to 1000rs :-) but they can pay 10$ very easily.

**Comment by ZainabDev** [comment]
i was talking that the paid courses should be seperate 
im not really planning to integrate such things in GPT right now im more focused on making everyone the best developer i can 
example arrange classes weekly online or physically to help juniors with c++ syntsx fundamentals etc and take quizes tests
and prepare them for gsoc, etc and guide them too


and im definitely integrating paid courses in codeneko which is a international company :)

**Comment by ZainabDev** [comment]
how do i contact you on WhatsApp we'll discuss in detail :)

**Comment by Zain-ul-din** [comment]
> i was talking that the paid courses should be seperate im not really planning to integrate such things in GPT right now im more focused on making everyone the best developer i can example arrange classes weekly online or physically to help juniors with c++ syntsx fundamentals etc and take quizes tests and prepare them for gsoc, etc and guide them too
> 
> and im definitely integrating paid courses in codeneko which is a international company :)

I like your good thoughts but in reality, nobody cares :-) I used to do free projects for students but after getting their stuff done they don't even like to talk with me. but I still think we should have a positive attitude and good luck with that.

**Comment by Zain-ul-din** [comment]
for contact run this code :-)

`[7, 9, 2, 7, 8, 2, 6, 1, 1, 3, 0].reverse()`

**Comment by ZainabDev** [comment]
now thats a strategy i caan do to random people who ask for number but shuffle it hehe

**Comment by Zain-ul-din** [comment]
this is not best strategy i would recommend encrypting it and then send since github or other big tech's are doing sementic analysis on the text I just want to prevent that

**Comment by Zain-ul-din** [comment]
re-open if like to.
